#! /bin/sh
#
# This script updates the application icons defined in
# install/nix/blue_nebula_**.png from a 1:1 ratio logo using ImageMagick.
#
# The sizes we want (used in the for loop) must also be defined in
# install_nix.cmake

for i in 16 32 48 64 128 256 512; do
    echo "Scaling icon to ${i}x${i}..."
    magick "$1" -resize "${i}x${i}" "../install/nix/blue-nebula_${i}.png"
done
echo "Done!"
