#include <algorithm>
#include <sys/time.h>
#include <random>
#include <iostream>

#include "cube.h"

int main(int argc, char **argv)
{
    std::string argv1;

    // generate key pair with random seed generated by OS
    if (argc == 1) {
        std::random_device rd;
        std::mt19937 mt(rd());
        std::uniform_int_distribution<> distribution(1, 255);
        std::generate_n(std::back_inserter(argv1), 255, [&]() { return distribution(mt); });
        argc = 2;
    } else {
        argv1 = argv[1];
    }

    // support --help/-h
    if (argv1 == "--help" || argv1 == "-h") {
        std::cerr << "Blue Nebula genkey utility" << std::endl;
        std::cerr << std::endl;
        std::cerr << "Usage:" << std::endl;
        std::cerr << std::endl;
        std::cerr << "  genkey                     generate private and public key using random seed" << std::endl;
        std::cerr << "  genkey <seed>              generate private and public key using provided seed" << std::endl;
        std::cerr << "  genkey <pubkey> <privkey>  check if public key belongs to private key" << std::endl;
        std::cerr << "  genkey -h/--help           print this help" << std::endl;
        return EXIT_SUCCESS;
    }

    // generate key pair with provided seed
    if(argc == 2) {
        vector<char> privkey, pubkey;
        genprivkey(argv1.c_str(), privkey, pubkey);
        printf("private key: %s\n", privkey.getbuf());
        printf("public key: %s\n", pubkey.getbuf());
        return EXIT_SUCCESS;
    }

    // print yes/no to match pubkey with privkey: genkey <pubkey> <privkey>
    if(argc == 3) {
        vector<char> pubkey;
        genpubkey(argv[2], pubkey);
        std::cerr << (argv1 == pubkey.data() ? "yes" : "no") << std::endl;
        return EXIT_SUCCESS;
    }

    // fallback
    std::cerr << "Error: unknown parameters, check " << argv[0] << " --help" << std::endl;
    return EXIT_FAILURE;
}
